<?php 
Route::group(['namespace'=>'Admin'],function () {
    Route::get('admin/user/userList','UserController@userList')->name('admin.user.userList')->middleware(["check.admin.login", "role.auth"]);
    Route::get('admin/user/roleGroupList','UserController@roleGroupList')->name('admin.user.roleGroupList')->middleware(["check.admin.login", "role.auth"]);
    Route::get('admin/user/roleGroupListSon','UserController@roleGroupListSon')->name('admin.user.roleGroupListSon')->middleware(["check.admin.login", "role.auth"]);
    Route::get('admin/home/default/index','Home\DefaultController@index')->name('admin.home.default.index');
    Route::get('admin/login/index','Login\LoginController@index')->name('admin.login.index')->middleware(["check.admin.login"]);
    Route::get('admin/home/index','Home\HomeController@index')->name('admin.home.index')->middleware(["check.admin.login"]);
    Route::get('admin/develop/index','DevelopController@index')->name('admin.develop.index')->middleware(["check.admin.login", "role.auth"]);
    Route::post('admin/develop/getRouteData','DevelopController@getRouteData')->name('admin.develop.getRouteData')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::get('admin/login/logout','Login\LoginController@logout')->name('admin.login.logout');
    Route::post('admin/login/login','Login\LoginController@login')->name('admin.login.login');
    Route::get('admin/develop/routeAdd','DevelopController@routeAdd')->name('admin.develop.routeAdd')->middleware(["check.admin.login", "role.auth"]);
    Route::post('admin/develop/saveData','DevelopController@saveData')->name('admin.develop.saveData')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::get('admin/user/roleList','UserController@roleList')->name('admin.user.roleList')->middleware(["check.admin.login", "role.auth"]);
    Route::post('admin/user/getRoleListData','UserController@getRoleListData')->name('admin.user.getRoleListData')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::get('admin/user/roleDetail','UserController@roleDetail')->name('admin.user.roleDetail')->middleware(["check.admin.login", "role.auth"]);
    Route::get('admin/user/getRuteData','UserController@getRuteData')->name('admin.user.getRuteData');
    Route::post('admin/user/roleDataSave','UserController@roleDataSave')->name('admin.user.roleDataSave')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::get('admin/error/index','ErrorController@index')->name('admin.error.index');
    Route::post('admin/user/getUserData','UserController@getUserData')->name('admin.user.getUserData')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::get('admin/user/userDetailAdd','UserController@userDetailAdd')->name('admin.user.userDetailAdd')->middleware(["check.admin.login", "role.auth"]);
    Route::post('admin/user/userDataSave','UserController@userDataSave')->name('admin.user.userDataSave')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::post('admin/user/userDataDel','UserController@userDataDel')->name('admin.user.userDataDel')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::get('admin/parameter/packages/index','Parameter\PackagesController@index')->name('admin.parameter.packages.index')->middleware(["check.admin.login", "role.auth"]);
    Route::post('admin/parameter/packages/getData','Parameter\PackagesController@getData')->name('admin.parameter.packages.getData')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::get('admin/parameter/packages/detail','Parameter\PackagesController@detail')->name('admin.parameter.packages.detail')->middleware(["check.admin.login", "role.auth"]);
    Route::post('admin/parameter/packages/save','Parameter\PackagesController@save')->name('admin.parameter.packages.save')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::post('admin/parameter/packages/del','Parameter\PackagesController@del')->name('admin.parameter.packages.del')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::get('admin/parameter/currency/index','Parameter\CurrencyController@index')->name('admin.parameter.currency.index')->middleware(["check.admin.login", "role.auth"]);
    Route::post('admin/parameter/currency/getData','Parameter\CurrencyController@getData')->name('admin.parameter.currency.getData')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::get('admin/im/test/index','Im\TestContrller@index')->name('admin.im.test.index')->middleware(["check.admin.login", "role.auth"]);
    Route::post('admin/im/test/getFriendList','Im\TestContrller@getFriendList')->name('admin.im.test.getFriendList');
    Route::post('admin/im/test/uploadImg','Im\TestContrller@uploadImg')->name('admin.im.test.uploadImg');
    Route::post('admin/im/test/uoloadFile','Im\TestContrller@uoloadFile')->name('admin.im.test.uoloadFile');
    Route::post('admin/im/test/getGroupUserList','Im\TestContrller@getGroupUserList')->name('admin.im.test.getGroupUserList');
    Route::post('admin/im/test/updateUserStatus','Im\TestContrller@updateUserStatus')->name('admin.im.test.updateUserStatus');
    Route::post('admin/im/test/updateUserSign','Im\TestContrller@updateUserSign')->name('admin.im.test.updateUserSign');
    Route::get('admin/im/test/chatLog','Im\TestContrller@chatLog')->name('admin.im.test.chatLog');
    Route::get('admin/home/home/editAvatar','Home\HomeController@editAvatar')->name('admin.home.home.editAvatar');
    Route::post('admin/home/home/uploadAvatar','Home\HomeController@uploadAvatar')->name('admin.home.home.uploadAvatar');
    Route::get('admin/parameter/currency/detail','Parameter\CurrencyController@detail')->name('admin.parameter.currency.detail')->middleware(["check.admin.login", "role.auth"]);
    Route::post('admin/parameter/currency/save','Parameter\CurrencyController@save')->name('admin.parameter.currency.save')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::post('admin/parameter/currency/del','Parameter\CurrencyController@del')->name('admin.parameter.currency.del')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::get('admin/parameter/country/index','Parameter\CountryController@index')->name('admin.parameter.country.index')->middleware(["check.admin.login", "role.auth"]);
    Route::post('admin/parameter/country/getData','Parameter\CountryController@getData')->name('admin.parameter.country.getData')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::get('admin/parameter/country/detail','Parameter\CountryController@detail')->name('admin.parameter.country.detail')->middleware(["check.admin.login", "role.auth"]);
    Route::post('admin/parameter/country/save','Parameter\CountryController@save')->name('admin.parameter.country.save')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::post('admin/parameter/country/del','Parameter\CountryController@del')->name('admin.parameter.country.del')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::get('admin/parameter/customs/index','Parameter\CustomsController@index')->name('admin.parameter.customs.index')->middleware(["check.admin.login", "role.auth"]);
    Route::post('admin/parameter/customs/getData','Parameter\CustomsController@getData')->name('admin.parameter.customs.getData')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::get('admin/parameter/customs/detail','Parameter\CustomsController@detail')->name('admin.parameter.customs.detail')->middleware(["check.admin.login", "role.auth"]);
    Route::post('admin/parameter/customs/save','Parameter\CustomsController@save')->name('admin.parameter.customs.save')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::post('admin/parameter/customs/del','Parameter\CustomsController@del')->name('admin.parameter.customs.del')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::get('admin/parameter/delcaration/index','Parameter\DelcarationController@index')->name('admin.parameter.delcaration.index')->middleware(["check.admin.login", "role.auth"]);
    Route::post('admin/parameter/delcaration/getData','Parameter\DelcarationController@getData')->name('admin.parameter.delcaration.getData')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::get('admin/parameter/delcaration/detail','Parameter\DelcarationController@detail')->name('admin.parameter.delcaration.detail')->middleware(["check.admin.login", "role.auth"]);
    Route::post('admin/parameter/delcaration/save','Parameter\DelcarationController@save')->name('admin.parameter.delcaration.save')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::post('admin/parameter/delcaration/del','Parameter\DelcarationController@del')->name('admin.parameter.delcaration.del')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::get('admin/parameter/destianation/index','Parameter\DestianationController@index')->name('admin.parameter.destianation.index')->middleware(["check.admin.login", "role.auth"]);
    Route::post('admin/parameter/destianation/getData','Parameter\DestianationController@getData')->name('admin.parameter.destianation.getData')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::get('admin/parameter/destianation/detail','Parameter\DestianationController@detail')->name('admin.parameter.destianation.detail')->middleware(["check.admin.login", "role.auth"]);
    Route::post('admin/parameter/destianation/save','Parameter\DestianationController@save')->name('admin.parameter.destianation.save')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::post('admin/parameter/destianation/del','Parameter\DestianationController@del')->name('admin.parameter.destianation.del')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::get('admin/parameter/exempted/index','Parameter\ExemptedController@index')->name('admin.parameter.exempted.index')->middleware(["check.admin.login", "role.auth"]);
    Route::post('admin/parameter/exempted/getData','Parameter\ExemptedController@getData')->name('admin.parameter.exempted.getData')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::get('admin/parameter/exempted/detail','Parameter\ExemptedController@detail')->name('admin.parameter.exempted.detail')->middleware(["check.admin.login", "role.auth"]);
    Route::post('admin/parameter/exempted/save','Parameter\ExemptedController@save')->name('admin.parameter.exempted.save')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::post('admin/parameter/exempted/del','Parameter\ExemptedController@del')->name('admin.parameter.exempted.del')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::get('admin/parameter/material/index','Parameter\MaterialController@index')->name('admin.parameter.material.index')->middleware(["check.admin.login", "role.auth"]);
    Route::post('admin/parameter/material/getData','Parameter\MaterialController@getData')->name('admin.parameter.material.getData')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::get('admin/parameter/material/detail','Parameter\MaterialController@detail')->name('admin.parameter.material.detail')->middleware(["check.admin.login", "role.auth"]);
    Route::post('admin/parameter/material/save','Parameter\MaterialController@save')->name('admin.parameter.material.save')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::post('admin/parameter/material/del','Parameter\MaterialController@del')->name('admin.parameter.material.del')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::get('admin/parameter/seaport/index','Parameter\SeaportController@index')->name('admin.parameter.seaport.index')->middleware(["check.admin.login", "role.auth"]);
    Route::post('admin/parameter/seaport/getData','Parameter\SeaportController@getData')->name('admin.parameter.seaport.getData')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::get('admin/parameter/seaport/detail','Parameter\SeaportController@detail')->name('admin.parameter.seaport.detail')->middleware(["check.admin.login", "role.auth"]);
    Route::post('admin/parameter/seaport/save','Parameter\SeaportController@save')->name('admin.parameter.seaport.save')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::post('admin/parameter/seaport/del','Parameter\SeaportController@del')->name('admin.parameter.seaport.del')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::get('admin/parameter/trade/index','Parameter\TradeController@index')->name('admin.parameter.trade.index')->middleware(["check.admin.login", "role.auth"]);
    Route::post('admin/parameter/trade/getData','Parameter\TradeController@getData')->name('admin.parameter.trade.getData')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::post('admin/parameter/trade/save','Parameter\TradeController@save')->name('admin.parameter.trade.save')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::get('admin/parameter/trade/detail','Parameter\TradeController@detail')->name('admin.parameter.trade.detail')->middleware(["check.admin.login", "role.auth"]);
    Route::post('admin/parameter/trade/del','Parameter\TradeController@del')->name('admin.parameter.trade.del')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::get('admin/parameter/transaction/index','Parameter\TransactionController@index')->name('admin.parameter.transaction.index')->middleware(["check.admin.login", "role.auth"]);
    Route::post('admin/parameter/transaction/getData','Parameter\TransactionController@getData')->name('admin.parameter.transaction.getData')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::get('admin/parameter/transaction/detail','Parameter\TransactionController@detail')->name('admin.parameter.transaction.detail')->middleware(["check.admin.login", "role.auth"]);
    Route::post('admin/parameter/transaction/save','Parameter\TransactionController@save')->name('admin.parameter.transaction.save')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::post('admin/parameter/transaction/del','Parameter\TransactionController@del')->name('admin.parameter.transaction.del')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::get('admin/parameter/transportation/index','Parameter\TransportationController@index')->name('admin.parameter.transportation.index')->middleware(["check.admin.login", "role.auth"]);
    Route::post('admin/parameter/transportation/getData','Parameter\TransportationController@getData')->name('admin.parameter.transportation.getData')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::get('admin/parameter/transportation/detail','Parameter\TransportationController@detail')->name('admin.parameter.transportation.detail')->middleware(["check.admin.login", "role.auth"]);
    Route::post('admin/parameter/transportation/save','Parameter\TransportationController@save')->name('admin.parameter.transportation.save')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::post('admin/parameter/transportation/del','Parameter\TransportationController@del')->name('admin.parameter.transportation.del')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::get('admin/parameter/unit/index','Parameter\UnitController@index')->name('admin.parameter.unit.index')->middleware(["check.admin.login", "role.auth"]);
    Route::post('admin/parameter/unit/getData','Parameter\UnitController@getData')->name('admin.parameter.unit.getData')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::get('admin/parameter/unit/detail','Parameter\UnitController@detail')->name('admin.parameter.unit.detail')->middleware(["check.admin.login", "role.auth"]);
    Route::post('admin/parameter/unit/save','Parameter\UnitController@save')->name('admin.parameter.unit.save')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::post('admin/parameter/unit/del','Parameter\UnitController@del')->name('admin.parameter.unit.del')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::get('admin/serviceparameters/shipper/index','ServiceParameters\ShipperController@index')->name('admin.serviceparameters.shipper.index')->middleware(["check.admin.login", "role.auth"]);
    Route::post('admin/serviceparameters/shipper/getData','ServiceParameters\ShipperController@getData')->name('admin.serviceparameters.shipper.getData')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::get('admin/serviceparameters/shipper/detail','ServiceParameters\ShipperController@detail')->name('admin.serviceparameters.shipper.detail')->middleware(["check.admin.login", "role.auth"]);
    Route::post('admin/serviceParameters/shipper/save','ServiceParameters\ShipperController@save')->name('admin.serviceparameters.shipper.save')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::post('admin/serviceParameters/shipper/del','ServiceParameters\ShipperController@del')->name('admin.serviceparameters.shipper.del')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::get('admin/serviceParameters/agencyShopServicer/index','ServiceParameters\AgencyShopServicerController@index')->name('admin.serviceParameters.agencyShopServicer.index')->middleware(["check.admin.login", "role.auth"]);
    Route::post('admin/serviceParameters/agencyShopServicer/index','ServiceParameters\AgencyShopServicerController@getData')->name('admin.serviceParameters.agencyShopServicer.getData')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::get('admin/serviceParameters/agencyShopServicer/detail','ServiceParameters\AgencyShopServicerController@detail')->name('admin.serviceParameters.agencyShopServicer.detail')->middleware(["check.admin.login", "role.auth"]);
    Route::post('admin/serviceParameters/agencyShopServicer/save','ServiceParameters\AgencyShopServicerController@save')->name('admin.serviceParameters.agencyShopServicer.save')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::post('admin/serviceParameters/agencyShopServicer/del','ServiceParameters\AgencyShopServicerController@del')->name('admin.serviceParameters.agencyShopServicer.del')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::get('admin/serviceParameters/manualInformation/index','ServiceParameters\ManualInformationController@index')->name('admin.serviceParameters.manualInformation.index')->middleware(["check.admin.login", "role.auth"]);
    Route::get('admin/serviceParameters/manualInformation/detail','ServiceParameters\ManualInformationController@detail')->name('admin.serviceParameters.manualInformation.detail')->middleware(["check.admin.login", "role.auth"]);
    Route::post('admin/serviceParameters/manualInformation/getData','ServiceParameters\ManualInformationController@getData')->name('admin.serviceParameters.manualInformation.getData')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::post('admin/serviceParameters/manualInformation/save','ServiceParameters\ManualInformationController@save')->name('admin.serviceParameters.manualInformation.save')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::post('admin/serviceParameters/manualInformation/del','ServiceParameters\ManualInformationController@del')->name('admin.serviceParameters.manualInformation.del')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::post('admin/serviceParameters/manualInformation/export','ServiceParameters\ManualInformationController@export')->name('admin.serviceParameters.manualInformation.export')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::post('admin/serviceParameters/manualInformation/import','ServiceParameters\ManualInformationController@import')->name('admin.serviceParameters.manualInformation.import')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
    Route::get('admin/customs/customsSplit/index','Customs\CustomsSplitController@index')->name('admin.customs.customsSplit.index')->middleware(["check.admin.login", "role.auth"]);
    Route::post('admin/customs/customsSplit/splitSave','Customs\CustomsSplitController@splitSave')->name('admin.customs.customsSplit.splitSave')->middleware(["check.admin.login.ajax", "role.auth.ajax"]);
});
